#!/usr/bin/python

import socket
import string
import struct
import sys

def printable(s):
    p = ''
    for c in s:
#if ord(c) >= 32 or ord(c) == 9:
        if c in string.printable:
            p += c
        else:
            break
    if len(p) < len(s):
        p += '...'
    return p


if len(sys.argv) != 3:
    print 'usage:', sys.argv[0], '<multicast group>', '<multicast port>'
    sys.exit(0)

mcast_group = sys.argv[1]
mcast_port = int(sys.argv[2])

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
#sock.bind(('', mcast_port))
sock.bind((mcast_group, mcast_port))
mreq = struct.pack('4sl', socket.inet_aton(mcast_group), socket.INADDR_ANY)

sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)

print 'listening for multicast data on', mcast_group, 'port', mcast_port

while True:
    msg = sock.recv(10240)
    print 'received', len(msg), 'bytes:', printable(msg)

